name: pull_down_button
description: Cupertino styled Pull-Down Button from iOS 14 with great customisation options.
version: 0.3.2
homepage: https://github.com/notDmDrl/pull_down_button
repository: https://github.com/notDmDrl/pull_down_button
issue_tracker: https://github.com/notDmDrl/pull_down_button/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: 3.0.0
